### ISSUE TITLE
Add jsoup dependency jar

### ISSUE THREAD

**Issue by dharmik16** [dharmik16/GetOpenIssueStats#5]

**Comment by scarabcoder** [comment]
Is this an issue? The way you worded it is a bit confusing.

**Comment by dharmik16** [comment]
@scarabcoder yeah its an issue.

**Comment by Nipel-Crumple** [comment]
@dharmik16, hi!
I'd like to work on this issue. Maybe it is a better way to add maven and all jsoup dependencies?

**Comment by dharmik16** [comment]
@Nipel-Crumple sure. Go ahead!

**Comment by kaaquist** [comment]
@dharmik16. I have created a branch of your project and added gradle to fix your dependency issue. Please let me push it to your repository.

**Comment by Nipel-Crumple** [comment]
Oops, I'm late...(

**Comment by dharmik16** [comment]
@kaaquist submit a pull request please. I will merge it.
